# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(650, 430)
        AboutDialog.setStyleSheet("background-color: rgb(32, 30, 41);\n"
"color: rgb(255, 255, 255);")
        self.textBrowser = QtWidgets.QTextBrowser(AboutDialog)
        self.textBrowser.setGeometry(QtCore.QRect(369, 10, 271, 211))
        self.textBrowser.setStyleSheet("background-color: rgb(66, 79, 131);")
        self.textBrowser.setObjectName("textBrowser")
        self.aboutLabel = QtWidgets.QLabel(AboutDialog)
        self.aboutLabel.setGeometry(QtCore.QRect(20, 10, 330, 300))
        self.aboutLabel.setText("")
        self.aboutLabel.setObjectName("aboutLabel")
        self.backButton = QtWidgets.QPushButton(AboutDialog)
        self.backButton.setGeometry(QtCore.QRect(410, 360, 196, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.backButton.setFont(font)
        self.backButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.backButton.setStyleSheet("background-color: rgb(66, 79, 131);")
        self.backButton.setObjectName("backButton")
        self.label2_2 = QtWidgets.QLabel(AboutDialog)
        self.label2_2.setGeometry(QtCore.QRect(375, 235, 136, 19))
        self.label2_2.setText("")
        self.label2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2_2.setObjectName("label2_2")
        self.modeBtn = QtWidgets.QPushButton(AboutDialog)
        self.modeBtn.setGeometry(QtCore.QRect(10, 380, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.modeBtn.setFont(font)
        self.modeBtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.modeBtn.setStyleSheet("background-color: rgb(66, 79, 131);")
        self.modeBtn.setObjectName("modeBtn")
        self.label3 = QtWidgets.QLabel(AboutDialog)
        self.label3.setGeometry(QtCore.QRect(20, 315, 136, 19))
        self.label3.setText("")
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName("label3")

        self.retranslateUi(AboutDialog)
        self.backButton.clicked.connect(AboutDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "关于"))
        self.backButton.setText(_translate("AboutDialog", "返     回"))
        self.modeBtn.setText(_translate("AboutDialog", "发布模式"))
