# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_config(object):
    def setupUi(self, config):
        config.setObjectName("config")
        config.resize(332, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(config.sizePolicy().hasHeightForWidth())
        config.setSizePolicy(sizePolicy)
        config.setStyleSheet("background-color: rgb(32, 30, 41);\n"
"color: rgb(255, 255, 255);")
        self.configEventButton = QtWidgets.QPushButton(config)
        self.configEventButton.setGeometry(QtCore.QRect(0, 0, 331, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.configEventButton.setFont(font)
        self.configEventButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.configEventButton.setStyleSheet("background-color: rgb(66, 79, 131);")
        self.configEventButton.setObjectName("configEventButton")
        self.configMachineButton = QtWidgets.QPushButton(config)
        self.configMachineButton.setGeometry(QtCore.QRect(0, 60, 331, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.configMachineButton.setFont(font)
        self.configMachineButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.configMachineButton.setStyleSheet("background-color: rgb(66, 79, 131);")
        self.configMachineButton.setObjectName("configMachineButton")
        self.backButton = QtWidgets.QPushButton(config)
        self.backButton.setGeometry(QtCore.QRect(0, 330, 331, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.backButton.setFont(font)
        self.backButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.backButton.setStyleSheet("background-color: rgb(66, 79, 131);")
        self.backButton.setObjectName("backButton")
        self.functionBtn = QtWidgets.QPushButton(config)
        self.functionBtn.setGeometry(QtCore.QRect(0, 120, 331, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.functionBtn.setFont(font)
        self.functionBtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.functionBtn.setStyleSheet("background-color: rgb(66, 79, 131);")
        self.functionBtn.setObjectName("functionBtn")
        self.aboutBtn = QtWidgets.QPushButton(config)
        self.aboutBtn.setGeometry(QtCore.QRect(0, 180, 331, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.aboutBtn.setFont(font)
        self.aboutBtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.aboutBtn.setStyleSheet("background-color: rgb(66, 79, 131);")
        self.aboutBtn.setObjectName("aboutBtn")

        self.retranslateUi(config)
        self.backButton.clicked.connect(config.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(config)

    def retranslateUi(self, config):
        _translate = QtCore.QCoreApplication.translate
        config.setWindowTitle(_translate("config", "配置"))
        self.configEventButton.setText(_translate("config", "赛     事"))
        self.configMachineButton.setText(_translate("config", "设     备"))
        self.backButton.setText(_translate("config", "返     回"))
        self.functionBtn.setText(_translate("config", "功    能"))
        self.aboutBtn.setText(_translate("config", "关    于"))
