# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'softwareUpdate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_softWareUpdate(object):
    def setupUi(self, softWareUpdate):
        softWareUpdate.setObjectName("softWareUpdate")
        softWareUpdate.resize(600, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(softWareUpdate.sizePolicy().hasHeightForWidth())
        softWareUpdate.setSizePolicy(sizePolicy)
        softWareUpdate.setStyleSheet("background-color: rgb(32, 30, 41);\n"
"color: rgb(255, 255, 255);")
        self.programFirmwareBtn = QtWidgets.QPushButton(softWareUpdate)
        self.programFirmwareBtn.setGeometry(QtCore.QRect(10, 120, 151, 60))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.programFirmwareBtn.setFont(font)
        self.programFirmwareBtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.programFirmwareBtn.setStyleSheet("background-color: rgb(66, 79, 131);")
        self.programFirmwareBtn.setObjectName("programFirmwareBtn")
        self.returnBtn = QtWidgets.QPushButton(softWareUpdate)
        self.returnBtn.setGeometry(QtCore.QRect(440, 330, 151, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.returnBtn.setFont(font)
        self.returnBtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.returnBtn.setStyleSheet("background-color: rgb(66, 79, 131);")
        self.returnBtn.setObjectName("returnBtn")
        self.label_states = QtWidgets.QLabel(softWareUpdate)
        self.label_states.setGeometry(QtCore.QRect(40, 220, 561, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_states.setFont(font)
        self.label_states.setText("")
        self.label_states.setAlignment(QtCore.Qt.AlignCenter)
        self.label_states.setObjectName("label_states")
        self.selectBtn = QtWidgets.QPushButton(softWareUpdate)
        self.selectBtn.setGeometry(QtCore.QRect(10, 20, 151, 60))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.selectBtn.setFont(font)
        self.selectBtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.selectBtn.setStyleSheet("background-color: rgb(66, 79, 131);")
        self.selectBtn.setObjectName("selectBtn")
        self.progressBar = QtWidgets.QProgressBar(softWareUpdate)
        self.progressBar.setGeometry(QtCore.QRect(180, 130, 401, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(softWareUpdate)
        QtCore.QMetaObject.connectSlotsByName(softWareUpdate)

    def retranslateUi(self, softWareUpdate):
        _translate = QtCore.QCoreApplication.translate
        softWareUpdate.setWindowTitle(_translate("softWareUpdate", "软件升级"))
        self.programFirmwareBtn.setText(_translate("softWareUpdate", "program\n"
" firmware"))
        self.returnBtn.setText(_translate("softWareUpdate", "back"))
        self.selectBtn.setText(_translate("softWareUpdate", "select\n"
" firmware"))
