# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shutdownDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shutDownDialog(object):
    def setupUi(self, shutDownDialog):
        shutDownDialog.setObjectName("shutDownDialog")
        shutDownDialog.resize(393, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(shutDownDialog.sizePolicy().hasHeightForWidth())
        shutDownDialog.setSizePolicy(sizePolicy)
        shutDownDialog.setStyleSheet("background-color: rgb(32, 30, 41);\n"
"color: rgb(255, 255, 255);")
        self.shutdownBtn = QtWidgets.QPushButton(shutDownDialog)
        self.shutdownBtn.setGeometry(QtCore.QRect(30, 130, 331, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.shutdownBtn.setFont(font)
        self.shutdownBtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.shutdownBtn.setStyleSheet("background-color: rgb(66, 79, 131);")
        self.shutdownBtn.setObjectName("shutdownBtn")
        self.rebootBtn = QtWidgets.QPushButton(shutDownDialog)
        self.rebootBtn.setGeometry(QtCore.QRect(30, 200, 331, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rebootBtn.setFont(font)
        self.rebootBtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.rebootBtn.setStyleSheet("background-color: rgb(66, 79, 131);")
        self.rebootBtn.setObjectName("rebootBtn")
        self.returnBtn = QtWidgets.QPushButton(shutDownDialog)
        self.returnBtn.setGeometry(QtCore.QRect(30, 320, 331, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.returnBtn.setFont(font)
        self.returnBtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.returnBtn.setStyleSheet("background-color: rgb(66, 79, 131);")
        self.returnBtn.setObjectName("returnBtn")
        self.label = QtWidgets.QLabel(shutDownDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 376, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(shutDownDialog)
        self.returnBtn.clicked.connect(shutDownDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(shutDownDialog)

    def retranslateUi(self, shutDownDialog):
        _translate = QtCore.QCoreApplication.translate
        shutDownDialog.setWindowTitle(_translate("shutDownDialog", "关机"))
        self.shutdownBtn.setText(_translate("shutDownDialog", "关机"))
        self.rebootBtn.setText(_translate("shutDownDialog", "重启"))
        self.returnBtn.setText(_translate("shutDownDialog", "返回"))
        self.label.setText(_translate("shutDownDialog", "先关闭系统后，用钥匙彻底关闭电源！"))
